export const actions = {
  LOADED_ACCOMMODATIONS: 'LOADED_ACCOMMODATIONS',
  LOADING_ACCOMMODATIONS: 'LOADING_ACCOMMODATIONS',
  ERROR_LOADING_ACCOMMODATIONS: 'ERROR_LOADING_ACCOMMODATIONS',
  FILTER_ACCOMMODATIONS: 'FILTER_ACCOMMODATIONS',
  SELECT_ACCOMMODATION: 'SELECT_ACCOMMODATION'
}